// AUTO-GENERATED by build_smart_env_config.js. DO NOT EDIT.
import { render as change_component } from '../src/components/change.js';
import { render as draft_creator_component } from '../src/components/draft_creator.js';

export const smart_env_config = {
  collections: {

  },
  item_types: {

  },
  components: {
    change: change_component,
    draft_creator: draft_creator_component
  }
};
